config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  resources :users, :except => [:index]
  resources :games, :except => [:edit, :update, :destroy] do
    resources :ships
    resources :shots, only: [:create, :index]
  end
  resources :sessions, only: [:new, :create]
  delete "/logout" => "sessions#destroy"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shots
  has_many :ships
  has_many :games, { foreign_key: :player1_id }
  has_many :wins, { foreign_key: :winner_id, class_name: "Game" }

  has_secure_password
  validates :username, :email, presence: true

	def total_wins
		Game.where(winner_id: self.id).to_a.length
	end

	def total_losses
		self.games.length - self.total_wins
	end 

	def total_shots_fired
	 	self.shots.length
	end

	def total_hits
		self.shots.where(hit: true).length
	end

	def total_misses
		self.total_shots_fired - self.total_hits
	end

	def game_shots_fired
		if self.games.last != nil
			g_id = self.games.last.id
			Game.find(g_id).shots.length
		else
			0
		end
	end

	def game_you_shots_fired
		if self.games.last != nil
			self.games.last.shots.length
		else
			0
		end
	end

	def game_opp_shots_fired
		self.game_shots_fired - self.game_you_shots_fired
	end

	def last_game_status
		if self.games.last != nil
			if self.id == self.games.last.winner_id
				"Won"
			else
				"Lost"
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :destroy]

  def show
    if session[:user_id] != params[:id].to_i
      redirect_to new_session_path
    end
    @game = Game.new
  end

  def new
    @user = User.new
  end

  def edit
    if session[:user_id] != params[:id].to_i
      redirect_to new_session_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if session[:user_id] != params[:id].to_i
      redirect_to new_session_path
    else
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        render :edit
      end
    end
  end

  def destroy
    if session[:user_id] != params[:id].to_i
      redirect_to new_session_path
    else
      if @user.destroy
        session[:user_id] = nil
        redirect_to root_path
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def find_user
      @user = User.find(params[:id])
    end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= render 'errors', :thing => @user %>
  <p>

    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/users/_stats.html.erb
<div class="container">

	<h2>User Stats:</h2>

	<div id="game-stats">
		<h3>Last Game Played:</h3>
		
		<li>Result: <%= current_user.last_game_status %> </li>
		<li>Total shots fired: <%= current_user.game_shots_fired %></li>
		<li>Shots fired by you: <%= current_user.game_you_shots_fired %></li>
		<li>Shots fired by opponent: <%= current_user.game_opp_shots_fired %></li>
		<li>Your ships sunk: TBD</li>
		<li>Opponent ships sunk: TBD</li>


	</div>

	<div id="overall-stats">
		<h3>Overall:</h3>
		
		<li>Total games played: <%= current_user.games.length %> </li>
		<li>Total wins: <%= current_user.total_wins%> </li> 
		<li>Total losses: <%= current_user.total_losses%> </li> 
		<li>Total shots fired: <%= current_user.total_shots_fired %> </li>
		<li>Total hits: <%= current_user.total_hits %> </li>
		<li>Total misses: <%= current_user.total_misses %> </li>

	</div>

</div>

app/views/users/edit.html.erb
<%= form_for @user  do |f| %>

  <%= render 'errors', :thing => @user %>
  <p>

    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 <% end %>

app/views/users/new.html.erb
<h2>Create new user!</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<div class= "new-game jumbotron">
  <%= form_for @game do |f| %>
  <%= f.submit %>
<% end %>

<%= link_to "List of games to Join", games_path%>

</div>

<%= link_to "Update Profile", edit_user_path(current_user) %>
<%= link_to "Delete Profile", @user, method: :delete, data: {confirm: "You sure?"} %>

<%= render partial: "stats" %>