config/routes.rb
Rails.application.routes.draw do
  root to: "games#index"
  resources :users, :except => [:index]
  resources :games, :except => [:edit, :update, :destroy] do
    resources :ships
    resources :shots, only: [:create, :index]
  end
  resources :sessions, only: [:new, :create]
  delete "/logout" => "sessions#destroy"

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :ships
  has_many :shots
  belongs_to :player1, class_name: 'User'
  belongs_to :player2, class_name: 'User'
  belongs_to :winner, class_name: 'User'

  validates :player1_id, presence: true

  def ready_to_join
    self.player2 == nil
  end

  def player1_ships
    self.player1.ships.where(game_id: self.id)
  end

  def player2_ships
    self.player2.ships.where(game_id: self.id)
  end

  def player1_dead_ships
    shippys = self.player1_ships.find_all {|ship| ship.dead == true}
  end

  def player1_lost
    player1_dead_ships.count >= 5
  end


  def player2_dead_ships
    shippys = self.player2_ships.find_all {|ship| ship.dead == true}
  end

  def player2_lost
    player2_dead_ships.count >= 5
  end

  def game_over
    if player1_lost
      return true
    elsif player2_lost
      return true
    end
  end

  def ready_to_start
    self.player1_ships.length == 5 && self.player2_ships.length == 5
  end

  def user_ships(user)
    self.ships.find_all {|ship| ship.user_id == user.id}
  end

  def ship_there?(user, ship)
    if user.id == self.player1.id
      user_ships = user_ships(user)
      used_ships = user_ships.map {|ship| ship.classification}
      used_ships.include?(ship.classification)
    elsif user.id == self.player2.id
      user_ships = user_ships(user)
      used_ships = user_ships.map {|ship| ship.classification}
      used_ships.include?(ship.classification)
    end
  end

  def who_fired_last
    if !self.shots.empty?
      self.shots.last.user.id
    end
  end

  def active_player
    if self.who_fired_last == self.player1_id
      self.player2.username
    elsif self.who_fired_last == nil
      self.player1.username
    else
      self.player1.username
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all.find_all {|game| game.ready_to_join == true}
  end

  def new
    @ship_1 = Ship.new
    @shot = Shot.new
    @game = Game.new

    render :new
  end



  def create
    @user = User.find_by(id: session[:user_id])
    if @user
      @game = Game.new(player1_id: @user.id)
      if @game.save
        redirect_to @game
      else
        render :index
      end
    else
      render :index
    end

  end

  def show
    @user = User.find_by(id: session[:user_id])
    @ship_1 = Ship.new
    @shot = Shot.new
    @game = Game.find(params[:id])
    if @game.ready_to_join
      @player2 = User.find(session[:user_id])
      if @player2 != @game.player1
        @game.player2_id = @player2.id
        @game.save
      end
    end
    if request.xhr?
        pl_ships = []
        op_ships = []
        pl_shots = []
        op_shots = []
      if @game.ready_to_join
        if @game.player1.id == session[:user_id]
          player = @game.player1.username
          pl_ships = @game.player1_ships
          pl_shots = @game.player1.shots.where(game_id: @game.id)
        end
        render json: { gameReady: !@game.ready_to_join, playerShips: pl_ships, opponentShips: op_ships, gameStart: @game.ready_to_start , player: player, activePlayer: @game.active_player, playerShots: pl_shots,opponentShots: op_shots}, status: 201
      else
        if @game.player1.id == session[:user_id]
          player = @game.player1.username
          pl_ships = @game.player1_ships
          pl_shots = @game.player1.shots.where(game_id: @game.id)
          op_ships = @game.player2_ships
          op_shots = @game.player2.shots.where(game_id: @game.id)

          render json: { gameReady: !@game.ready_to_join, playerShips: pl_ships, opponentShips: op_ships, gameStart: @game.ready_to_start ,player: player, activePlayer: @game.active_player, playerShots: pl_shots,opponentShots: op_shots}, status: 201

        elsif @game.player2.id == session[:user_id]
          player = @game.player2.username
          pl_ships = @game.player2_ships
          pl_shots = @game.player2.shots.where(game_id: @game.id)
          op_ships = @game.player1_ships
          op_shots = @game.player1.shots.where(game_id: @game.id)

          render json: { gameReady: !@game.ready_to_join, playerShips: pl_ships, opponentShips: op_ships, gameStart: @game.ready_to_start ,player: player, activePlayer: @game.active_player, playerShots: pl_shots,opponentShots: op_shots}, status: 201

        end

      end
    else
      render :show
    end
  end

  private

  def game_params
    params.require(:game).permit(:player1_id)
  end
end

app/views/games/index.html.erb
<% if logged_in? %>
  <ul>
  <% @games.each do |game| %>
    <li><%= link_to "Join the game with #{game.player1.username}", game_path(game)%></li>
  <% end %>
  </ul>
<% end %>

app/views/games/new.html.erb
<center>


<%= form_for @ship_1, name: "Carrier" do |f| %>
<%= f.hidden_field :classification, value: "carrier" %>
<%= f.submit %>
<% end %>

<%= form_for @ship_1, id: "Battleship" do |f| %>
<%= f.hidden_field :classification, value: "battleship" %>
<%= f.submit %>
<% end %>

<%= form_for @ship_1, id: "Cruiser" do |f| %>
<%= f.hidden_field :classification, value: "cruiser" %>
<%= f.submit %>
<% end %>

<%= form_for @ship_1, id: "Submarine" do |f| %>
<%= f.hidden_field :classification, value: "submarine" %>
<%= f.submit %>
<% end %>

<%= form_for @ship_1, id: "Destroyer" do |f| %>
<%= f.hidden_field :classification, value: "destroyer" %>
<%= f.submit %>
<% end %>




<table id="player_1" class="table-bordered">
  <tr id="header">
    <th>Row 1</th>
    <th>Row 2</th>
    <th>Row 3</th>
    <th>Row 4</th>
    <th>Row 5</th>
    <th>Row 6</th>
    <th>Row 7</th>
    <th>Row 8</th>
  </tr>
  <tr id="row_one" value="1">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
  <tr id="row_two" value="2">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_three" value="3">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_four" value="4">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_five" value="5">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_six" value="6">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
  <tr id="row_seven" value="7">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_eight" value="8">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
</table>

<br><br><br><br>

<table id="player_2" class="table-bordered">
   <tr id="header">
    <th>Row 1</th>
    <th>Row 2</th>
    <th>Row 3</th>
    <th>Row 4</th>
    <th>Row 5</th>
    <th>Row 6</th>
    <th>Row 7</th>
    <th>Row 8</th>
  </tr>
  <tr id="row_one" value="1">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
  <tr id="row_two" value="2">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_three" value="3">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_four" value="4">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_five" value="5">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_six" value="6">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
  <tr id="row_seven" value="7">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>
    <tr id="row_eight" value="8">
    <td>Row 1</td>
    <td>Row 2</td>
    <td>Row 3</td>
    <td>Row 4</td>
    <td>Row 5</td>
    <td>Row 6</td>
    <td>Row 7</td>
    <td>Row 8</td>
  </tr>

</table>
</center>

<div id="ok">0</div>

<%= form_for @shot, id: "fire" do |f| %>
<%= f.submit %>
<% end %>

app/views/games/show.html.erb
<center>



<%= form_for [@game, @ship_1], name: "Carrier" do |f| %>
<%= f.hidden_field :classification, value: "carrier" %>
<%= f.submit "Create a carrier" %>
<% end %>

<%= form_for [@game, @ship_1], id: "Battleship" do |f| %>
<%= f.hidden_field :classification, value: "battleship" %>
<%= f.submit "Create a battleship" %>
<% end %>

<%= form_for [@game, @ship_1], id: "Cruiser" do |f| %>
<%= f.hidden_field :classification, value: "cruiser" %>
<%= f.submit "Create a cruiser" %>
<% end %>

<%= form_for [@game, @ship_1], id: "Submarine" do |f| %>
<%= f.hidden_field :classification, value: "submarine" %>
<%= f.submit "Create a Submarine" %>
<% end %>

<%= form_for [@game, @ship_1], id: "Destroyer" do |f| %>
<%= f.hidden_field :classification, value: "destroyer" %>
<%= f.submit "Create a Destroyer"%>
<% end %>


<h1 id="playername" name="<%= @user.username %>">Get Ready to play!</h1>


  <table id="opponent" class="table-bordered">
    <tr id="header">
      <th></th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 5 </th>
      <th> 6 </th>
      <th> 7 </th>
      <th> 8 </th>
    </tr>
    <tr id="row_one" value="1">
      <td>A</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_two" value="2">
      <td>B</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>

    <tr id="row_three" value="3">
      <td>C</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_four" value="4">
      <td>D</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_five" value="5">
      <td>E</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_six" value="6">
      <td>F</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_seven" value="7">
      <td>G</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_eight" value="8">
      <td>H</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
  </table>

  <br><br><br><br>

  <table id="player" class="table-bordered">
    <tr id="header">
      <th></th>
      <th> 1 </th>
      <th> 2 </th>
      <th> 3 </th>
      <th> 4 </th>
      <th> 5 </th>
      <th> 6 </th>
      <th> 7 </th>
      <th> 8 </th>
    </tr>
    <tr id="row_one" value="1">
      <td>A</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_two" value="2">
      <td>B</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_three" value="3">
      <td>C</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_four" value="4">
      <td>D</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_five" value="5">
      <td>E</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_six" value="6">
      <td>F</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_seven" value="7">
      <td>G</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
    <tr id="row_eight" value="8">
      <td>H</td>
      <td class="space column_1" value="1">Row 1</td>
      <td class="space column_2" value="2">Row 2</td>
      <td class="space column_3" value="3">Row 3</td>
      <td class="space column_4" value="4">Row 4</td>
      <td class="space column_5" value="5">Row 5</td>
      <td class="space column_6" value="6">Row 6</td>
      <td class="space column_7" value="7">Row 7</td>
      <td class="space column_8" value="8">Row 8</td>
    </tr>
  </table>
</center>